// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAljsJ9FcLu6fWFtR1dcNW_rHSVRwKrYDI',
    appId: '1:433034435806:web:5f186743771611d612364f',
    messagingSenderId: '433034435806',
    projectId: 'lifelog-capstone',
    authDomain: 'lifelog-capstone.firebaseapp.com',
    storageBucket: 'lifelog-capstone.firebasestorage.app',
    measurementId: 'G-C9LWXYDE9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzspQJw3K-FJA0WBAGbNUzLseZRJMNGJM',
    appId: '1:433034435806:android:805f354a62100bab12364f',
    messagingSenderId: '433034435806',
    projectId: 'lifelog-capstone',
    storageBucket: 'lifelog-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx9-Udi6XKogXzL3Ea-CksiV1FCaf-wAw',
    appId: '1:433034435806:ios:39fdafd41eaaa92912364f',
    messagingSenderId: '433034435806',
    projectId: 'lifelog-capstone',
    storageBucket: 'lifelog-capstone.firebasestorage.app',
    iosBundleId: 'com.example.lifelog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx9-Udi6XKogXzL3Ea-CksiV1FCaf-wAw',
    appId: '1:433034435806:ios:dfc0e9016f91db1e12364f',
    messagingSenderId: '433034435806',
    projectId: 'lifelog-capstone',
    storageBucket: 'lifelog-capstone.firebasestorage.app',
    iosBundleId: 'com.example.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAljsJ9FcLu6fWFtR1dcNW_rHSVRwKrYDI',
    appId: '1:433034435806:web:1ab3963cbb5bc58b12364f',
    messagingSenderId: '433034435806',
    projectId: 'lifelog-capstone',
    authDomain: 'lifelog-capstone.firebaseapp.com',
    storageBucket: 'lifelog-capstone.firebasestorage.app',
    measurementId: 'G-0SNT3EXRHR',
  );
}
